# Generated by Django 4.2 on 2026-04-14 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fiidiidata',
            new_name='data_ingest_date_e30441_idx',
            old_name='data_ingest_date_889a20_idx',
        ),
        migrations.RenameIndex(
            model_name='fiidiidata',
            new_name='data_ingest_source_6524a2_idx',
            old_name='data_ingest_source_8f59e8_idx',
        ),
    ]
