"""
ASGI config for CRPMS.

Routes HTTP requests to the standard Django ASGI application and WebSocket
connections to Django Channels via the dashboard routing table.

See: https://docs.djangoproject.com/en/4.2/howto/deployment/asgi/
     https://channels.readthedocs.io/en/stable/
"""

import os

from channels.auth import AuthMiddlewareStack
from channels.routing import ProtocolTypeRouter, URLRouter
from channels.security.websocket import AllowedHostsOriginValidator
from django.core.asgi import get_asgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')

# Import WebSocket URL patterns from the dashboard app routing module.
# Add new WebSocket routes there — do not edit this file for route changes.
from apps.dashboard.routing import websocket_urlpatterns  # noqa: E402

application = ProtocolTypeRouter({
    # HTTP → standard Django request/response stack
    'http': get_asgi_application(),

    # WebSocket → Channels stack with session auth and host validation
    'websocket': AllowedHostsOriginValidator(
        AuthMiddlewareStack(
            URLRouter(websocket_urlpatterns)
        )
    ),
})
