# Generated by Django 4.2 on 2026-03-07 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(choices=[('market_risk', 'Market Risk'), ('sentiment', 'Sentiment'), ('fundamental', 'Fundamental'), ('opportunity', 'Opportunity')], max_length=20)),
                ('score', models.FloatField()),
                ('band', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10, null=True)),
                ('flags', models.JSONField(default=dict)),
                ('raw_data', models.JSONField(default=dict)),
                ('is_stale', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Agent Output',
                'verbose_name_plural': 'Agent Outputs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('RISK_CRITICAL', 'Risk Critical'), ('RISK_HIGH', 'Risk High'), ('OPPORTUNITY', 'Opportunity'), ('STOP_LOSS', 'Stop Loss'), ('EVENT_RISK', 'Event Risk')], max_length=15)),
                ('message', models.TextField()),
                ('threshold_breached', models.FloatField(blank=True, null=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('starting_capital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sharpe_ratio', models.FloatField(blank=True, null=True)),
                ('cagr', models.FloatField(blank=True, null=True)),
                ('max_drawdown', models.FloatField(blank=True, null=True)),
                ('win_rate', models.FloatField(blank=True, null=True)),
                ('capital_utilisation', models.FloatField(blank=True, null=True)),
                ('config', models.JSONField(default=dict)),
                ('benchmark_results', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Backtest Result',
                'verbose_name_plural': 'Backtest Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataIngestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=50)),
                ('ticker', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('records_fetched', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Data Ingestion Log',
                'verbose_name_plural': 'Data Ingestion Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('HOLD', 'Hold'), ('REDUCE', 'Reduce'), ('EXIT', 'Exit'), ('INCREASE', 'Increase'), ('REALLOCATE', 'Reallocate')], max_length=15)),
                ('confidence_score', models.FloatField(default=0)),
                ('reasoning_text', models.TextField(blank=True)),
                ('input_signals', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Decision Log',
                'verbose_name_plural': 'Decision Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FeatureSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('risk_features', models.JSONField(default=dict)),
                ('sentiment_features', models.JSONField(default=dict)),
                ('fundamental_features', models.JSONField(default=dict)),
                ('opportunity_features', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Feature Snapshot',
                'verbose_name_plural': 'Feature Snapshots',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FundamentalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('debt_ratio', models.FloatField(blank=True, null=True)),
                ('roe', models.FloatField(blank=True, null=True)),
                ('pe_ratio', models.FloatField(blank=True, null=True)),
                ('net_margin', models.FloatField(blank=True, null=True)),
                ('promoter_pledge_pct', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fundamental Data',
                'verbose_name_plural': 'Fundamental Data',
                'ordering': ['-period'],
            },
        ),
        migrations.CreateModel(
            name='MacroIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('date', models.DateField()),
                ('source', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Macro Indicator',
                'verbose_name_plural': 'Macro Indicators',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField()),
                ('source', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('published_at', models.DateTimeField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('content_hash', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_capital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('available_capital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioStateSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_data', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Portfolio State Snapshot',
                'verbose_name_plural': 'Portfolio State Snapshots',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('avg_buy_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('allocation_pct', models.FloatField(default=0)),
                ('unrealised_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Price History',
                'verbose_name_plural': 'Price History',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SectorMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=100)),
                ('sub_sector', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Sector Mapping',
                'verbose_name_plural': 'Sector Mappings',
            },
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('reddit', 'Reddit'), ('stocktwits', 'StockTwits')], max_length=15)),
                ('text', models.TextField()),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('mention_count', models.IntegerField(default=1)),
                ('upvotes', models.IntegerField(default=0)),
                ('content_hash', models.CharField(max_length=64, unique=True)),
                ('posted_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Social Post',
                'verbose_name_plural': 'Social Posts',
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('sub_sector', models.CharField(blank=True, max_length=100)),
                ('exchange', models.CharField(default='NSE', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Watchlist',
                'verbose_name_plural': 'Watchlist',
                'ordering': ['ticker'],
            },
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['ticker'], name='portfolio_w_ticker_edcdb5_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['sector'], name='portfolio_w_sector_f8bdc4_idx'),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='ticker_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='portfolio.watchlist', to_field='ticker'),
        ),
        migrations.AddField(
            model_name='sectormapping',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_mappings', to='portfolio.watchlist', to_field='ticker'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='portfolio.watchlist', to_field='ticker'),
        ),
        migrations.AddField(
            model_name='position',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='portfolio.portfolio'),
        ),
        migrations.AddField(
            model_name='position',
            name='watchlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='portfolio.watchlist', to_field='ticker'),
        ),
        migrations.AddField(
            model_name='portfoliostatesnapshot',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_snapshots', to='portfolio.portfolio'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['name'], name='portfolio_p_name_3ff523_idx'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='ticker_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_articles', to='portfolio.watchlist', to_field='ticker'),
        ),
        migrations.AddIndex(
            model_name='macroindicator',
            index=models.Index(fields=['indicator_name', 'date'], name='portfolio_m_indicat_727adf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='macroindicator',
            unique_together={('indicator_name', 'date')},
        ),
        migrations.AddField(
            model_name='fundamentaldata',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundamental_data', to='portfolio.watchlist', to_field='ticker'),
        ),
        migrations.AddField(
            model_name='featuresnapshot',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_snapshots', to='portfolio.watchlist', to_field='ticker'),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_logs', to='portfolio.watchlist', to_field='ticker'),
        ),
        migrations.AddIndex(
            model_name='dataingestionlog',
            index=models.Index(fields=['source_name', 'timestamp'], name='portfolio_d_source__5c492a_idx'),
        ),
        migrations.AddIndex(
            model_name='dataingestionlog',
            index=models.Index(fields=['status', 'timestamp'], name='portfolio_d_status_95d3d0_idx'),
        ),
        migrations.AddIndex(
            model_name='backtestresult',
            index=models.Index(fields=['run_name'], name='portfolio_b_run_nam_01c437_idx'),
        ),
        migrations.AddIndex(
            model_name='backtestresult',
            index=models.Index(fields=['created_at'], name='portfolio_b_created_d9f5b4_idx'),
        ),
        migrations.AddField(
            model_name='alert',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='portfolio.watchlist', to_field='ticker'),
        ),
        migrations.AddField(
            model_name='agentoutput',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_outputs', to='portfolio.watchlist', to_field='ticker'),
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['ticker_tag', 'posted_at'], name='portfolio_s_ticker__882546_idx'),
        ),
        migrations.AddIndex(
            model_name='sectormapping',
            index=models.Index(fields=['sector'], name='portfolio_s_sector_a75cc7_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['ticker', 'date'], name='portfolio_p_ticker__2fa202_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricehistory',
            unique_together={('ticker', 'date')},
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['portfolio'], name='portfolio_p_portfol_c88a21_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('portfolio', 'watchlist')},
        ),
        migrations.AddIndex(
            model_name='portfoliostatesnapshot',
            index=models.Index(fields=['portfolio', 'timestamp'], name='portfolio_p_portfol_d0f8cf_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['ticker_tag', 'published_at'], name='portfolio_n_ticker__d58373_idx'),
        ),
        migrations.AddIndex(
            model_name='fundamentaldata',
            index=models.Index(fields=['ticker', 'period'], name='portfolio_f_ticker__ca84ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fundamentaldata',
            unique_together={('ticker', 'period')},
        ),
        migrations.AddIndex(
            model_name='featuresnapshot',
            index=models.Index(fields=['ticker', 'date'], name='portfolio_f_ticker__2c5354_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='featuresnapshot',
            unique_together={('ticker', 'date')},
        ),
        migrations.AddIndex(
            model_name='decisionlog',
            index=models.Index(fields=['ticker', 'timestamp'], name='portfolio_d_ticker__00439f_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['ticker', 'alert_type', 'created_at'], name='portfolio_a_ticker__619106_idx'),
        ),
        migrations.AddIndex(
            model_name='agentoutput',
            index=models.Index(fields=['ticker', 'agent_name', 'timestamp'], name='portfolio_a_ticker__5a1d54_idx'),
        ),
    ]
